# Site settings
baseurl: "/"
url: "https://imranh.co.uk"

title: Imran's Website
show_excerpts: true

# Build settings
markdown: kramdown
remote_theme: imranh2/plainwhite-jekyll

plainwhite:
  name: Imran Hussain
  tagline: Random Musings...
  social_links:
    twitter: imranh2
    github: imranh2
    #linkedIn:
  navigation:
    - title: About
      url: "/about"
